version: 2
jobs:
  build:
    docker:
      - image: argvc/pipenv-alpine-python2

    steps:
      - checkout
      - run: apk add --update --no-cache g++ gcc libxslt-dev
      - run: make deps
      - run: make test
